### ISSUE TITLE
changes to "About" section

### ISSUE THREAD

**Issue by aristiles** [CSSDevConf/2017-CSSDevConf-Site#1]
The Numerous Benefits of CSS Dev Conf
Impressive amount of expertise against the background of the French Quarter

Knowledgeable speakers

Curated Keynote Speakers, Featured Presenters, and Workshop Leaders are chosen from among the brightest minds and seasoned experts working in CSS today.

Voter-approved sessions

The CSS Community—people just like you—submit session ideas and vote on their favorites to complete the conference schedule.

Picture perfect setting

As one of the last family-owned hotels in the French Quarter, the historic Hotel Monteleone, with its world-famous Carousel Bar, is one of the first landmarks in the city of New Orleans.

A great value

A full Breakfast, Delicious Snacks, and Evening Events for each conference day are included in the price of your ticket. Plus, hotel rooms start at only $189.00 per night!

Best of the best

Attendees vote for their favorite track sessions anonymously, and the most popular sessions of CSS Dev Conf will be repeated on Day Two, in case you miss them the first time.

Latest and greatest CSS

CSS Dev Conf is the place to learn new techniques, whether you need to improve everyday workflow or learn the cutting-edge specifications landing in browser nightly builds.

**Comment by teleject** [comment]
Updated.
